name: Add Bug Label on Comment
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'

    - name: Make a comment and add label
      run: |
        import os
        from ghapi.core import GhApi

        comment_body = os.getenv('COMMENT_BODY', '')
        issue_number = int(os.getenv('ISSUE_NUMBER', 0))
        owner, repo = os.getenv('REPO', '').split('/')

        api = GhApi(owner=owner, repo=repo)

        if '/bug' in comment_body:
          api.issues.add_labels(issue_number, labels=['bug'])
      env:
        COMMENT_BODY: ${{ github.event.comment.body }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
