name: Add Bug Label on Comment
on:
  pull_request:
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write  

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 'latest'

    - name: install dependencies
      run: pip install ghapi

    - name: see payload # for debugging purposes only
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}

    - name: Make a comment and add label
      run: |
        import os
        from ghapi.core import GhApi

        comment_body = os.getenv('COMMENT_BODY', '')
        issue_number = int(os.getenv('ISSUE_NUMBER', 0))
        owner, repo = os.environ['REPO'].split('/')

        api = GhApi(owner=owner, repo=repo, token=os.getenv('GITHUB_TOKEN'))

        if '/bug' in comment_body:
          api.issues.add_labels(issue_number, labels=['bug'])

      env:
        COMMENT_BODY: ${{ github.event.comment.body }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}

         print("Comment Body:", comment_body)
         print("Issue number:", issue_number)
         print("Github token:", GITHUB_TOKEN)
         print("REPO:", repository)
