name: Add Bug Label on Comment
on:
  issue_comment:
     types: [created]
  workflow_dispatch:

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with: 
         python-version: '3.x'

    - name: Make a comment and add label
      run: |
        import os
        import json
        from ghapi.core import GhApi

        comment_body = os.environ.get('COMMENT_BODY', '')
        issue_number = int(os.environ.get('ISSUE_NUMBER', 0))
        owner, repo = os.environ['REPO'].split('/')

        api = GhApi(owner=owner, repo=repo)

        if '/bug' in comment_body:
           api.issues.add_labels(issue_number, labels=['bug'])
